#!/bin/bash

#Defaults:


Mask="D*NEF"
C=0
Folder=''


#Inputs:

while [[ $# -gt 0 ]]; do
  case "$1" in
    --mask|-m)
      Mask="$2"
      shift 2
      ;;
    --folder|-f)
      Folder="$2"
      shift 2
      ;;
    --help|-h)
      echo "Usage: $0 --mask <pattern> --folder <Folder>"
      echo "example: $0 --mask"'"D*NEF"' --folder "/tmp/DSC/"
      exit 0
      ;;
    *)
      echo "❌ unexpected : $1"
      echo "try: $0 --mask <pattern>"
      exit 1
      ;;
  esac
done

MainRun() {
  local Folder="${1:-.}"
  local Mask="${2:-*}"

  Folder="${Folder%/}/"
  shopt -s nullglob

  local Files=("$Folder"$Mask)
  local CounterT=${#Files[@]}
  local C=0

  echo "📂 Folder: $Folder"
  echo "🔍 Found $CounterT files matching: $Mask"
  echo

  for f in "${Files[@]}"; do
    [ -e "$f" ] || continue
    [ -d "$FILE" ] && continue
    ((C++))
    printf "[%02d/%02d] %s\n" "$C" "$CounterT" "$f"

    datetime=$(exiftool -s -s -s -DateTimeOriginal "$f" | tr ' :|' '.')
    if [ -n "$datetime" ]; then
      basename=$(basename "$f")
      newname="${Folder}${datetime}_${basename}"
      mv -v "$f" "$newname"
    else
      echo "⚠️  No EXIF date for $f"
    fi
  done
}


MainRun 