#!/bin/bash

#Defaults:

Mask="_D,D"
Type="JPG,jpg,NEF,nef"

while [[ $# -gt 0 ]]; do
  case "$1" in
    --mask)
      mask="$2"
      shift 2
      ;;
    --type)
      type="$2"
      shift 2
      ;;
    --help|-h)
      echo "Usage: $0 --mask <pattern> --type <type>"
      echo "example: $0 --mask D --type JPG"
      echo "or:"
      echo "example: $0 "'--mask "D,_D,dsc" --type "JPG,jpg,NEF,nef"'
      exit 0
      ;;
    *)
      echo "❌ unexpected : $1"
      echo "try: $0 --mask <pattern> --type <type>"
      exit 1
      ;;
  esac
done




for f in {$Mask}*{$Type}; do
  [ -e "$f" ] || continue
  echo $f
  datetime=$(exiftool -s -s -s -DateTimeOriginal $f | tr ":\| " ".")
  if [ -n "$datetime" ]; then
    mv -v "$f" "${datetime}_${f}"
  else
    echo "⚠️ No EXIF DATE for $f"
  fi

done
